"""Forest-adventure notification lines. Single source of truth.

The embed description is one random line per notification, with NAME
replaced by the creator's Creator Name (fallback: bare platform handle).
Served to the dashboard via GET /api/wildlines so the Defaults live
preview draws from the same list.
"""
import random

WILD_LINES = (
    "NAME Has Started a Forest Expedition!",
    "NAME Has Begun Their Journey!",
    "NAME Has Set Foot in the Wild!",
    "NAME Has Entered the Forest!",
    "NAME Has Discovered the Wild!",
    "NAME Has Gone Beyond the Trees!",
    "NAME Has Taken to the Woods!",
    "NAME Has Embarked on a Journey!",
    "NAME's Wild Journey Begins!",
    "NAME's Forest Adventure Begins!",
    "NAME's Journey Into the Wild!",
    "NAME's Great Forest Adventure!",
    "NAME's Wilderness Expedition!",
    "NAME just entered the forest!",
    "NAME just ventured into the wild!",
    "NAME just started an adventure!",
    "NAME is exploring new territory!",
    "NAME is venturing beyond the trees!",
    "NAME is exploring the wilderness!",
    "NAME has entered unexplored territory!",
    "NAME is on a forest expedition!",
    "NAME is discovering new paths!",
    "NAME is exploring the unknown!",
    "NAME is venturing deeper!",
    "NAME is heading into the woods!",
    "NAME is exploring the untamed wild!",
    "NAME is following the forest trail!",
    "NAME is blazing a new trail!",
    "NAME is venturing off the beaten path!",
    "NAME is exploring beyond the trail!",
    "NAME is deep in an adventure!",
    "NAME is discovering what lies beyond!",
    "NAME is calling you into the wild!",
    "NAME is Live in the Wild!",
    "NAME Has Entered the Wild!",
    "NAME is Exploring the Forest!",
    "NAME is Live in the Woods!",
    "NAME is Out in the Wild!",
    "NAME is Deep in the Forest!",
    "NAME is Exploring the Wild!",
    "NAME is Roaming the Forest!",
    "NAME is Adventuring in the Wild!",
    "NAME is Live Among the Trees!",
    "NAME is Wandering the Woods!",
    "NAME is Exploring the Wilderness!",
    "NAME is Lost in the Wild!",
    "NAME is Deep in the Woods!",
    "NAME is On a Wild Adventure!",
    "NAME is Venturing into the Forest!",
    "NAME is Out Exploring!",
    "NAME is Journeying Through the Wild!",
    "NAME is Trekking Through the Forest!",
    "NAME is Roaming the Wilderness!",
    "Join NAME's Wild Adventure!",
    "Follow NAME Into the Wild!",
    "Join NAME in the Forest!",
    "Adventure With NAME!",
    "Explore With NAME!",
    "Venture With NAME!",
    "Journey With NAME!",
    "Enter the Wild With NAME!",
    "Explore the Forest With NAME!",
    "Join NAME on Their Adventure!",
    "Follow NAME's Adventure!",
    "Join NAME's Forest Journey!",
    "Step Into NAME's Adventure!",
    "Venture Into the Woods With NAME!",
    "Discover the Wild With NAME!",
    "Explore the Unknown With NAME!",
    "Journey Into the Wild With NAME!",
    "Go Wild With NAME!",
    "Take a Walk on the Wild Side With NAME!",
    "The Adventure Awaits With NAME!",
    "NAME is Live!",
    "NAME is Out There!",
    "NAME is in the Wild!",
    "NAME is Exploring!",
    "NAME is Adventuring!",
    "NAME is Wandering!",
    "NAME is Roaming!",
    "NAME is Trekking!",
    "NAME is Venturing!",
    "NAME is On the Move!",
    "NAME is Off Exploring!",
    "NAME is Beyond the Trees!",
    "NAME is Into the Wild!",
    "NAME is Beyond the Woods!",
    "NAME is Under the Canopy!",
    "NAME is Among the Trees!",
    "NAME is Deep in the Wild!",
    "NAME is On a Journey!",
    "NAME is Exploring New Ground!",
    "NAME is Discovering the Wild!",
    "The Wild Awaits NAME!",
    "The Forest Awaits NAME!",
    "The Woods Are Calling NAME!",
    "NAME Answers the Call of the Wild!",
    "NAME Has Gone Into the Wild!",
    "NAME Has Wandered Into the Woods!",
    "NAME Has Set Out on an Adventure!",
)


def random_wild_line(name: str) -> str:
    """One random line with NAME filled in (never empty, never raw)."""
    clean = (name or "").strip() or "someone"
    return random.choice(WILD_LINES).replace("NAME", clean)
